@startuml

autonumber

actor 提议者A
actor 提议者B

提议者A -> 接受者A: 发送准备请求 [1, ]
接受者A -> 接受者A: 当前无提案, 记录提案 1
接受者A -> 提议者A: [尚无提案]承诺不会响应编号 <= 1 的提案, 且不会通过提案编号 < 1 的提案

提议者A -> 接受者B: 发送准备请求 [1, ]
接受者B -> 接受者B: 当前无提案, 记录提案 1
接受者B -> 提议者A: [尚无提案]承诺不会响应编号 <= 1 的提案, 且不会通过提案编号 < 1 的提案

提议者B -> 接受者C: 发送准备请求 [5, ]
接受者C -> 接受者C: 当前无提案, 记录提案 5
接受者C -> 提议者B: [尚无提案]承诺不会响应编号 <= 5 的提案, 且不会通过提案编号 < 5 的提案

提议者B -> 接受者B: 发送准备请求 [5, ]
接受者B -> 接受者B: 新提案编号大于当前响应的最大提案, 且当前无通过提案, 记录提案 5
接受者B -> 提议者B: [尚无提案]承诺不会响应编号 <= 5 的提案, 且不会通过编号 <5 的提案

提议者B -> 接受者C: 发送准备请求 [5, ]
接受者C -> 接受者C: 当前无提案, 记录提案 5
接受者C -> 提议者B: [尚无提案]承诺不会响应编号 <= 5 的提案, 且不会通过编号 <5 的提案

提议者A -> 接受者C: 发送准备请求 [1, ]
接受者C -> 接受者C: 新提案编号小于当前响应的最大提案, 不做响应

提议者A -> 提议者A: 收到集群内大多数节点的响应

提议者A -> 接受者A: 发送接受请求[1, 3]
接受者A -> 接受者A: 提案编号小于之前承诺的 5, 提议被拒绝

提议者A -> 接受者B: 发送接受请求[1, 3]
接受者B -> 接受者B: 提案编号小于之前承诺的 5, 提议被拒绝

提议者A -> 接受者C: 发送接受请求[1, 3]
接受者C -> 接受者C: 提案编号小于之前承诺的 5, 提议被拒绝

提议者B -> 提议者B: 收到集群内大多数节点的响应

提议者B -> 接受者A: 发送接受请求[5, 7]
接受者A -> 接受者A: 提案编号符合承诺, 通过提案[5, 7]

提议者B -> 接受者B: 发送接受请求[5, 7]
接受者B -> 接受者B: 提案编号符合承诺, 通过提案[5, 7]

提议者B -> 接受者C: 发送接受请求[5, 7]
接受者C -> 接受者C: 提案编号符合承诺, 通过提案[5, 7]
@enduml