@startuml
'autonumber

== 初始选举阶段 ==
A -> A: 在等待领导者心跳超时后\n增加自己的任期编号, 并推举自己为候选人, 先给自己投上一票
note left: 任期编号:1\n选票:1
A -> B: 请求投票
A -> C: 请求投票
B -> B: 在任期 1 内没有进行过投票, 将选票投给 A, 并增加自己的任期编号
note left: 任期编号:1\n选票:1
B --> A: 投票给 A
C -> C: 在任期 1 内没有进行过投票, 将选票投给 A, 并增加自己的任期编号
note left: 任期编号:1\n选票:1
C --> A: 投票给 A
A -> A: 在选举超时时间内赢得了大多数选票, 成为本届任期内的新领导者

loop 周期性发送心跳, 阻止跟随者发起新的选举
A -> B: 心跳信息
A -> C: 心跳信息
end
@enduml